version: '3.6'
services:
  db:
    image: supabase/postgres:latest
    container_name: supabase_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"

  api:
    image: supabase/postgrest:latest
    container_name: supabase_api
    depends_on:
      - db
    environment:
      PGRST_DB_URI: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres"
      PGRST_DB_SCHEMA: "public"
      PGRST_JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8000:8000"

  storage:
    image: supabase/storage-api:latest
    container_name: supabase_storage
    depends_on:
      - db
    environment:
      ANON_KEY: ${ANON_KEY}
      SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
      POSTGREST_URL: "http://api:8000"
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres"
    ports:
      - "5000:5000"
